# Generated by Django 4.1.7 on 2023-05-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=100, unique=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=512)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
