# Generated by Django 4.1.7 on 2023-05-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(to='core.platform'),
        ),
    ]
