# Generated by Django 4.1.7 on 2023-06-12 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_game_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.genre'),
            preserve_default=False,
        ),
    ]
