# Generated by Django 4.1.7 on 2023-05-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_developer_genre_platform_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(default='2020-10-10'),
        ),
    ]
